### ISSUE TITLE
Black Screen Bug (When looking around)

### ISSUE THREAD

**Issue by GabenCrying** [mastercomfig/mastercomfig#407]
**Describe the bug**
Any mastercomfig preset results in a odd black screen glitch
**How you encountered the issue**
Installing any preset 

**Screenshots**
https://www.youtube.com/watch?v=edyLdumbWwE   -- I created a video to depict the issue since it is only active in motion and looking towards specific parts of the map...? I am assuming it is a cosmetic breaking something, however even combined with various no hats/cosmetics mods, no fix.

**Desktop (please complete the following information):**
* Config version:  9.0.0
* Config preset and addon(s): Low, Ultra-low, Medium
* Custom values (if any): multiple selected OR none selected (Doesn't help it seems)
* DX level: opengl 
* Launch options:
* Operating system (OS): GNU/Linux
* Graphics card (GPU): Radeon VII
* Graphics driver version: AMDGPU
* Processor (CPU): Ryzen 5 1600X
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 8GB

So as you can see by the video, it is where I look that creates the black buggy screen. I have tried this on three separate distros this week on clean Tf2 installs. Any help would be really appreciated!

**Comment by micwoj92** [comment]
This is mesa issue afaik, the temporary solution is to use higher preset or downgrade your driver.

**Comment by mastercoms** [comment]
This is a Mesa bug. https://gitlab.freedesktop.org/mesa/mesa/-/issues/3514

Downgrade away from Mesa 20.2.

**Comment by GabenCrying** [comment]
> This is mesa issue afaik, the temporary solution is to use higher preset or downgrade your driver.



> This is a [Mesa bug](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3514). Downgrade away from Mesa 20.2.
> 
> You will see this issue less with `lighting_ex=high` (which sets `mat_phong 1`), but you will still see it occasionally even with those settings.


Thank you for the super speed responses! So currently this isn't a real cure, more of a roll the dice sort of thing? It isn't all the time it happens and only started happening maybe two months ago. but yeah I will play with mesa. Thank you again!

**Comment by treacherousfiend** [comment]
this isn't something we can fix, as its an issue with mesa and not mastercomfig.

**Comment by GabenCrying** [comment]
> this isn't something we can fix, as its an issue with mesa and not mastercomfig.

Roger Dodger! Thank you again for your fast responses, all. Have a wonderful rest of the day

**Comment by GabenCrying** [comment]
guys i still need help

**Comment by micwoj92** [comment]
This is not mastercomfig issue, please use mesa bugtracker.

**Comment by gmod64bit** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3514#note_702564

### **_CURE_**

**Comment by jason0597** [comment]
I'm running into these issues as well. I thought it was my GPU dying, but then I thought to remove mastercomfig and see if it fixed it. I was really surprised when it did! Thought it was a mastercomfig bug, so I came here.
Alas, it's a mesa bug, and I do indeed run Linux. But it's good to know it's not my GPU that's dying.
