### ISSUE TITLE
Network issue w/ player collision 

### ISSUE THREAD

**Issue by GabenCrying** [mastercomfig/mastercomfig#644]
**Describe the bug**
Player animation radically delayed, more so than usual, as well as player model clipping  

**How you encountered the issue**
I only play spy, and backpeddling players as well as any contact movement based manuevers feel like im rubber banding in and out of them which makes backstabs difficult

**Screenshots**
Only a video would suffice, here is thy link!
https://www.youtube.com/watch?v=5HBN5g_llec
Note the crit sound in failstabs 

**Desktop (please complete the following information):** 
* mastercomfig version: mastercomfig version : 9.1.0 | November 1, 2020 
* Preset and addon(s): Low preset  | Addons: NoTutorial, Mouse Movement Tweak, No Extra Models
* Custom values (if any): None
* DX level: OpenGL
* Launch options: None
* Operating system (OS): GNU {Linux} Gentoo
* Graphics card (GPU): 2080ti
* Graphics driver version: Nvidia Linux-x86_64 11.515.43.04
* Processor (CPU): Ryzen 9 3700X
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

I'm assuming this is a network setting but I can't figure it out. I tried lowering  cl_interp 
to 0, the lowest it goes though is 15.x but whateva

**Comment by mastercoms** [comment]
This is just an issue with the game itself, due to player movement prediction collision. Are you sure this only happens with mastercomfig?

**Comment by GabenCrying** [comment]
> This likely is just an issue with the game itself, due to player movement prediction collision. Are you sure this only happens with mastercomfig? See if cl_showerror 2 displays any output when you encounter this issue.

Hey! Actually I'm not entire certain anymore. I do NOT have this problem at all on official casual servers, but it seems to be prevelent on community servers exclusively. I don't know what to blame this on. Leaning towards community servers. I am going to test that showerror command in about 30 minutes from now, will update then!

**Comment by GabenCrying** [comment]
Well, I got pred errors on a lot of stabs, then I looked in to that and found 

cl_pred_optimize 

changing that to 1 rather than 2 seems to have helped a great deal, does that add up or is this placebo

**Comment by mastercoms** [comment]
That makes sense. 2 basically allows some error to add up to a certain point before correcting. 1 will just correct immediately. I think at some point in comfig we did use cl_pred_optimize 1 for all classes and it had some issues. However, having it for just spy makes a lot of sense, since the tiny errors don't act in your favor as spy, since the angles can be on the edge of a backstab.

**Comment by RicochetYT** [comment]
I've noticed similar issues while playing, myself, and I'm curious if setting cl_pred_optimize to 1 will actually help Spy, as it's probably one of the one things I've not tested. I'll test around with this.
